# Generated by Django 5.0.6 on 2026-08-28 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کلاس')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='مدت هر جلسه (دقیقه)')),
                ('base_fee', models.PositiveIntegerField(verbose_name='هزینه پایه هر جلسه (تومان)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='RateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تعرفه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قالب تعرفه',
                'verbose_name_plural': 'قالب\u200cهای تعرفه',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('face_encodings', models.JSONField(blank=True, default=list)),
                ('warning_interval_hours', models.PositiveIntegerField(default=24)),
                ('last_warning_sent', models.DateTimeField(blank=True, null=True)),
                ('warning_enabled', models.BooleanField(default=True)),
                ('credit_limit', models.IntegerField(default=0, verbose_name='رد لاین (سقف بدهی)')),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'هنرجو',
                'verbose_name_plural': 'هنرجویان',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('specialization', models.CharField(max_length=100, verbose_name='تخصص/ساز')),
                ('commission_percent', models.PositiveIntegerField(default=30, verbose_name='درصد سهم استاد')),
                ('initial_balance', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('session_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('fee', models.PositiveIntegerField()),
                ('verification_method', models.CharField(choices=[('face', 'تشخیص چهره'), ('code', 'کد تایید'), ('manual', 'دستی')], default='face', max_length=20)),
                ('face_verified', models.BooleanField(default=False)),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.teacher')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
                'ordering': ['-session_date'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='rate_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ratetemplate', verbose_name='قالب تعرفه'),
        ),
        migrations.CreateModel(
            name='SessionVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to='core.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('settlement_type', models.CharField(choices=[('cash', 'نقد'), ('check', 'چک'), ('promissory', 'سفته'), ('credit', 'نسیه'), ('card', 'کارت به کارت')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('overdue', 'سررسید گذشته')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('warning_sent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='core.teacher')),
            ],
            options={
                'verbose_name': 'تسویه',
                'verbose_name_plural': 'تسویه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.teacher'),
        ),
        migrations.CreateModel(
            name='TeacherEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('is_settled', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classsession')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='core.teacher')),
            ],
            options={
                'verbose_name': 'درآمد استاد',
                'verbose_name_plural': 'درآمدهای اساتید',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'شارژ'), ('debit', 'کسر'), ('refund', 'بازگشت')], max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('payment_method', models.CharField(default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='core.student')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='TeacherRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.PositiveIntegerField(verbose_name='تعرفه ساعتی (تومان)')),
                ('rate_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_rates', to='core.ratetemplate')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.teacher')),
            ],
            options={
                'verbose_name': 'تعرفه استاد',
                'verbose_name_plural': 'تعرفه\u200cهای اساتید',
                'unique_together': {('teacher', 'rate_template')},
            },
        ),
    ]
