# Generated by Django 5.0.6 on 2026-08-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_absencerequest_sessionswaprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='receipt_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه عکس رسید'),
        ),
    ]
