# Generated by Django 5.0.6 on 2026-08-31 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wallettransaction_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionswaprequest',
            name='preferred_end',
            field=models.TimeField(blank=True, null=True, verbose_name='تا ساعت'),
        ),
        migrations.AddField(
            model_name='sessionswaprequest',
            name='preferred_start',
            field=models.TimeField(blank=True, null=True, verbose_name='از ساعت'),
        ),
        migrations.AddField(
            model_name='sessionswaprequest',
            name='target_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='core.student', verbose_name='هنرجوی هدف'),
        ),
        migrations.AlterField(
            model_name='sessionswaprequest',
            name='preferred_times',
            field=models.JSONField(blank=True, default=list, verbose_name='ساعت\u200cهای پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='sessionswaprequest',
            name='target_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_to', to='core.classsession', verbose_name='جلسه هدف'),
        ),
    ]
