# Generated by Django 5.0.6 on 2026-09-01 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sessionswaprequest_preferred_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='verification_method',
            field=models.CharField(choices=[('face', 'تشخیص چهره'), ('code', 'کد تایید'), ('manual', 'دستی'), ('absent_authorized', 'غیبت موجه'), ('absent_unauthorized', 'غیبت غیرموجه')], default='face', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='base_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه پایه (اختیاری - اگر تعرفه استاد نبود)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rate_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ratetemplate', verbose_name='قالب تعرفه'),
        ),
        migrations.AlterField(
            model_name='sessionverificationcode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
